diccionario={
    "a": "ei",
    "b": "bi",
    "c": "si",
    "d": "di",
    "e": "i",
    "f": "ef",
    "g": "yi",
    "h": "eich",
    "i": "ai",
    "j": "yei",
    "k": "kei",
    "l": "el",
    "m": "em",
    "n": "en",
    "o": "ou",
    "p": "pi",
    "q": "kiu",
    "r": "ar",
    "s": "es",
    "t": "ti",
    "u": "iu",
    "v": "vi",
    "w": "dábol iu",
    "x": "eks",
    "y": "uai",
    "z": "zi"
}