diccionario = {
    "dog": "a",
    "cat": "a",
    "eagle": "an",
    "university": "a",
    "apple": "an",
    "orange": "an",
    "egg": "an",
    "idea": "an",
    "elephant": "an",
    "car": "a",
    "house": "a",
    "tree": "a",
    "pencil": "a",
    "book": "a",
    "phone": "a",
    "doctor": "a",
    "teacher": "a",
    "table": "a",
    "chair": "a",
    "glass": "a",
    "plate": "a",
    "friend": "a",
    "road": "a",
    "park": "a",
    "shop": "a",
    "cake": "a",
    "bag": "a",
    "flower": "a",
    "tiger": "a",
    "computer": "a",
    "camera": "a",
    "hotel": "a",
    "river": "a",
    "mountain": "a",
    "city": "a",
    "student": "a",
    "school": "a",
    "bike": "a",
    "lamp": "a",
    "sweater": "a",
    "door": "a",
    "ladder": "a",
    "party": "a",
    "train": "a",
    "movie": "a",
    "artist": "an",
    "actor": "an",
    "aunt": "an",
    "engineer": "an",
    "hour": "an",
    "honor": "an",
    "island": "an",
    "umbrella": "an",
    "eagle": "an",
    "airplane": "an",
    "insect": "an",
    "oven": "an",
    "example": "an",
    "onion": "an",
    "astronaut": "an",
    "octopus": "an",
    "event": "an",
    "error": "an",
    "engine": "an",
    "alarm": "an",
    "uncle": "an",
    "invitation": "an",
    "accident": "an",
    "opportunity": "an",
    "announcement": "an",
    "article": "an",
    "angel": "an",
    "eye": "an",
    "organization": "an",
    "answer": "an",
    "architect": "an",
    "orchestra": "an",
    "avenue": "an",
    "opinion": "an",
    "operation": "an",
    "university": "a",
    "European trip": "a",
    "useful tool": "a",
    "uniform": "a",
    "unicorn": "a",
    "historic event": "a",
    "heir": "an",
    "hotel": "a",
    "honor": "an",
    "it's _ apple": "an",
    "it's _ book": "a",
    "it's _ car": "a",
    "it's _ elephant": "an",
    "it's _ hour": "an",
    "it's _ idea": "an",
    "it's _ dog": "a",
    "it's _ umbrella": "an",
    "it's _ interesting concept": "an",
    "it's _ orange": "an",
    "it's _ cat": "a",
    "it's _ elephant's tusk": "an",
    "it's _ university": "a",
    "it's _ hotel": "a",
    "it's _ interesting topic": "an",
    "it's _ old problem": "an",
    "it's _ email": "an",
    "it's _ event": "an",
    "it's _ opportunity": "an",
    "it's _ university professor": "a",
    "it's _ unusual circumstance": "an",
    "it's _ ice cream": "an",
    "it's _ idea that I like": "an",
    "it's _ honor": "an",
    "it's _ honest mistake": "an",
    "it's _ agreement": "an",
    "it's _ job": "a",
    "it's _ office": "an",
    "it's _ honest question": "an",
    "it's _ busy day": "a",
    "it's _ yellow car": "a",
    "it's _ open question": "an",
    "it's _ large house": "a",
    "it's _ excellent opportunity": "an",
    "it's _ odd proposal": "an",
    "it's _ new perspective": "a",
    "it's _ old tradition": "an",
    "it's _ interesting observation": "an",
    "it's _ evening": "an",
    "it's _ exciting discovery": "an",
    "it's _ difficult task": "a",
    "it's _ accurate statement": "an",
    "it's _ amazing place": "an",
    "it's _ unusual request": "an",
    "it's _ beautiful evening": "a",
    "it's _ strong opinion": "a",
    "it's _ amazing feeling": "an",
    "it's _ unique experience": "an",
    "it's _ unusual way": "an",
    "it's _ exciting challenge": "an",
    "it's _ old trick": "an",
    "it's _ expensive item": "an",
    "it's _ optimistic choice": "an",
    "it's _ pleasant surprise": "a",
    "it's _ accurate measurement": "an",
    "it's _ big mistake": "a",
    "it's _ odd request": "an",
    "it's _ unexpected outcome": "an",
    "it's _ useful idea": "an",
    "it's _ rare event": "a",
    "it's _ small issue": "a",
    "it's _ innovative strategy": "an",
    "it's _ good decision": "a",
    "it's _ modern approach": "a",
    "it's _ excellent tool": "an",
    "it's _ simple solution": "a",
    "it's _ beautiful idea": "a",
    "it's _ impressive result": "an",
    "it's _ new chapter": "a",
    "it's _ confusing problem": "a",
    "it's _ powerful argument": "a",
    "it's _ useful feature": "a",
    "it's _ dramatic change": "a",
    "it's _ educational resource": "an",
    "it's _ logical explanation": "a",
    "it's _ satisfying answer": "a",
    "it's _ creative idea": "a",
    "it's _ helpful suggestion": "a",
    "it's _ personal touch": "a",
    "it's _ new concept": "a",
    "it's _ surprising result": "a",
    "it's _ interesting article": "an",
    "it's _ constructive feedback": "an",
    "it's _ important change": "an",
    "it's _ formal request": "a",
    "it's _ productive conversation": "a",
    "it's _ long journey": "a",
    "it's _ bad idea": "a",
    "it's _ rewarding task": "a",
    "it's _ beautiful solution": "a",
    "it's _ thoughtful gesture": "a",
    "it's _ new beginning": "a",
    "it's _ challenging situation": "a",
    "it's _ crucial moment": "a",
    "it's _ new perspective": "an",
    "it's _ unexpected result": "an",
    "it's _ detailed report": "a",
    "it's _ random idea": "a",
    "it's _ historical event": "a",
    "it's _ quiet night": "a",
    "it's _ elaborate plan": "an",
    "it's _ nice surprise": "a",
    "it's _ particular case": "a",
    "it's _ curious situation": "an",
    "it's _ positive change": "a",
    "it's _ different story": "a",
    "it's _ clear explanation": "a",
    "it's _ valuable insight": "a",
    "it's _ favorite topic": "a",
    "it's _ critical moment": "a",
    "it's _ rare opportunity": "a",
    "it's _ intriguing idea": "an",
    "it's _ strange feeling": "a",
    "it's _ large scale": "a",
    "it's _ historic achievement": "an",
    "it's _ new product": "a",
    "it's _ major improvement": "a"
}