diccionario={
    '1': 'one', '2': 'two', '3': 'three', '4': 'four', '5': 'five', 
    '6': 'six', '7': 'seven', '8': 'eight', '9': 'nine', '10': 'ten',
    '11': 'eleven', '12': 'twelve', '13': 'thirteen', '14': 'fourteen', '15': 'fifteen', 
    '16': 'sixteen', '17': 'seventeen', '18': 'eighteen', '19': 'nineteen', '20': 'twenty',
    '21': 'twenty-one', '22': 'twenty-two', '23': 'twenty-three', '24': 'twenty-four', '25': 'twenty-five',
    '26': 'twenty-six', '27': 'twenty-seven', '28': 'twenty-eight', '29': 'twenty-nine', '30': 'thirty',
    '31': 'thirty-one', '32': 'thirty-two', '33': 'thirty-three', '34': 'thirty-four', '35': 'thirty-five',
    '36': 'thirty-six', '37': 'thirty-seven', '38': 'thirty-eight', '39': 'thirty-nine', '40': 'forty',
    '41': 'forty-one', '42': 'forty-two', '43': 'forty-three', '44': 'forty-four', '45': 'forty-five', 
    '46': 'forty-six', '47': 'forty-seven', '48': 'forty-eight', '49': 'forty-nine', '50': 'fifty',
    '51': 'fifty-one', '52': 'fifty-two', '53': 'fifty-three', '54': 'fifty-four', '55': 'fifty-five', 
    '56': 'fifty-six', '57': 'fifty-seven', '58': 'fifty-eight', '59': 'fifty-nine', '60': 'sixty',
    '61': 'sixty-one', '62': 'sixty-two', '63': 'sixty-three', '64': 'sixty-four', '65': 'sixty-five',
    '66': 'sixty-six', '67': 'sixty-seven', '68': 'sixty-eight', '69': 'sixty-nine', '70': 'seventy',
    '71': 'seventy-one', '72': 'seventy-two', '73': 'seventy-three', '74': 'seventy-four', '75': 'seventy-five', 
    '76': 'seventy-six', '77': 'seventy-seven', '78': 'seventy-eight', '79': 'seventy-nine', '80': 'eighty',
    '81': 'eighty-one', '82': 'eighty-two', '83': 'eighty-three', '84': 'eighty-four', '85': 'eighty-five', 
    '86': 'eighty-six', '87': 'eighty-seven', '88': 'eighty-eight', '89': 'eighty-nine', '90': 'ninety',
    '91': 'ninety-one', '92': 'ninety-two', '93': 'ninety-three', '94': 'ninety-four', '95': 'ninety-five', 
    '96': 'ninety-six', '97': 'ninety-seven', '98': 'ninety-eight', '99': 'ninety-nine', '100': 'one hundred',
    '113': 'one hundred thirteen', 
    '125': 'one hundred twenty-five',
    '157': 'one hundred fifty-seven', 
    '212': 'two hundred twelve', 
    '237': 'two hundred thirty-seven',
    '258': 'two hundred fifty-eight', 
    '276': 'two hundred seventy-six', 
    '303': 'three hundred three', 
    '325': 'three hundred twenty-five', 
    '356': 'three hundred fifty-six',
    '384': 'three hundred eighty-four', 
    '402': 'four hundred two', 
    '423': 'four hundred twenty-three', 
    '467': 'four hundred sixty-seven', 
    '489': 'four hundred eighty-nine',
    '503': 'five hundred three', 
    '527': 'five hundred twenty-seven', 
    '549': 'five hundred forty-nine', 
    '601': 'six hundred one', 
    '625': 'six hundred twenty-five',
    '673': 'six hundred seventy-three', 
    '702': 'seven hundred two', 
    '729': 'seven hundred twenty-nine', 
    '758': 'seven hundred fifty-eight', 
    '804': 'eight hundred four',
    '837': 'eight hundred thirty-seven', 
    '859': 'eight hundred fifty-nine', 
    '902': 'nine hundred two', 
    '937': 'nine hundred thirty-seven', 
    '963': 'nine hundred sixty-three',
    '978': 'nine hundred seventy-eight', 
    '990': 'nine hundred ninety', 
    '222': 'two hundred twenty-two', 
    '333': 'three hundred thirty-three', 
    '444': 'four hundred forty-four',
    '555': 'five hundred fifty-five', 
    '666': 'six hundred sixty-six', 
    '777': 'seven hundred seventy-seven', 
    '888': 'eight hundred eighty-eight', 
    '999': 'nine hundred ninety-nine',
    '321': 'three hundred twenty-one', 
    '654': 'six hundred fifty-four', 
    '876': 'eight hundred seventy-six', 
    '189': 'one hundred eighty-nine', 
    '271': 'two hundred seventy-one',
    '312': 'three hundred twelve', 
    '489': 'four hundred eighty-nine', 
    '591': 'five hundred ninety-one', 
    '673': 'six hundred seventy-three', 
    '784': 'seven hundred eighty-four',
    '1001': 'one thousand one',
    '1023': 'one thousand twenty-three',
    '1056': 'one thousand fifty-six',
    '1109': 'one thousand one hundred nine',
    '1210': 'one thousand two hundred ten',
    '1357': 'one thousand three hundred fifty-seven',
    '1432': 'one thousand four hundred thirty-two',
    '1567': 'one thousand five hundred sixty-seven',
    '1724': 'one thousand seven hundred twenty-four',
    '1809': 'one thousand eight hundred nine',
    '1932': 'one thousand nine hundred thirty-two',
    '2045': 'two thousand forty-five',
    '2187': 'two thousand one hundred eighty-seven',
    '2346': 'two thousand three hundred forty-six',
    '2489': 'two thousand four hundred eighty-nine',
    '2598': 'two thousand five hundred ninety-eight',
    '2765': 'two thousand seven hundred sixty-five',
    '2891': 'two thousand eight hundred ninety-one',
    '3012': 'three thousand twelve',
    '3157': 'three thousand one hundred fifty-seven',
    '3264': 'three thousand two hundred sixty-four',
    '3409': 'three thousand four hundred nine',
    '3521': 'three thousand five hundred twenty-one',
    '3678': 'three thousand six hundred seventy-eight',
    '3804': 'three thousand eight hundred four',
    '3967': 'three thousand nine hundred sixty-seven',
    '4020': 'four thousand twenty',
    '4163': 'four thousand one hundred sixty-three',
    '4329': 'four thousand three hundred twenty-nine',
    '4482': 'four thousand four hundred eighty-two',
    '4593': 'four thousand five hundred ninety-three',
    '4706': 'four thousand seven hundred six',
    '4870': 'four thousand eight hundred seventy',
    '4938': 'four thousand nine hundred thirty-eight',
    '5014': 'five thousand fourteen',
    '5189': 'five thousand one hundred eighty-nine',
    '5276': 'five thousand two hundred seventy-six',
    '5432': 'five thousand four hundred thirty-two',
    '5570': 'five thousand five hundred seventy',
    '5698': 'five thousand six hundred ninety-eight',
    '5831': 'five thousand eight hundred thirty-one',
    '5960': 'five thousand nine hundred sixty',
    '6023': 'six thousand twenty-three',
    '6175': 'six thousand one hundred seventy-five',
    '6309': 'six thousand three hundred nine',
    '6472': 'six thousand four hundred seventy-two',
    '6521': 'six thousand five hundred twenty-one',
    '6648': 'six thousand six hundred forty-eight',
    '6790': 'six thousand seven hundred ninety',
    '6874': 'six thousand eight hundred seventy-four',
    '7005': 'seven thousand five',
    '7159': 'seven thousand one hundred fifty-nine',
    '7236': 'seven thousand two hundred thirty-six',
    '7382': 'seven thousand three hundred eighty-two',
    '7498': 'seven thousand four hundred ninety-eight',
    '7624': 'seven thousand six hundred twenty-four',
    '7777': 'seven thousand seven hundred seventy-seven',
    '7819': 'seven thousand eight hundred nineteen',
    '7901': 'seven thousand nine hundred one',
    '8013': 'eight thousand thirteen',
    '8147': 'eight thousand one hundred forty-seven',
    '8295': 'eight thousand two hundred ninety-five',
    '8350': 'eight thousand three hundred fifty',
    '8468': 'eight thousand four hundred sixty-eight',
    '8542': 'eight thousand five hundred forty-two',
    '8619': 'eight thousand six hundred nineteen',
    '8754': 'eight thousand seven hundred fifty-four',
    '8896': 'eight thousand eight hundred ninety-six',
    '9025': 'nine thousand twenty-five',
    '9163': 'nine thousand one hundred sixty-three',
    '9218': 'nine thousand two hundred eighteen',
    '9374': 'nine thousand three hundred seventy-four',
    '9462': 'nine thousand four hundred sixty-two',
    '9578': 'nine thousand five hundred seventy-eight',
    '9631': 'nine thousand six hundred thirty-one',
    '9742': 'nine thousand seven hundred forty-two',
    '9859': 'nine thousand eight hundred fifty-nine',
    '9964': 'nine thousand nine hundred sixty-four',
    '10001': 'ten thousand one',
    '10567': 'ten thousand five hundred sixty-seven',
    '11234': 'eleven thousand two hundred thirty-four',
    '11890': 'eleven thousand eight hundred ninety',
    '12345': 'twelve thousand three hundred forty-five',
    '13000': 'thirteen thousand',
    '14567': 'fourteen thousand five hundred sixty-seven',
    '15000': 'fifteen thousand',
    '16001': 'sixteen thousand one',
    '17890': 'seventeen thousand eight hundred ninety',
    '18543': 'eighteen thousand five hundred forty-three',
    '19000': 'nineteen thousand',
    '20005': 'twenty thousand five',
    '21345': 'twenty-one thousand three hundred forty-five',
    '22000': 'twenty-two thousand',
    '23456': 'twenty-three thousand four hundred fifty-six',
    '24567': 'twenty-four thousand five hundred sixty-seven',
    '25000': 'twenty-five thousand',
    '26890': 'twenty-six thousand eight hundred ninety',
    '27543': 'twenty-seven thousand five hundred forty-three',
    '28900': 'twenty-eight thousand nine hundred',
    '30012': 'thirty thousand twelve',
    '31456': 'thirty-one thousand four hundred fifty-six',
    '32000': 'thirty-two thousand',
    '34567': 'thirty-four thousand five hundred sixty-seven',
    '35678': 'thirty-five thousand six hundred seventy-eight',
    '37000': 'thirty-seven thousand',
    '38543': 'thirty-eight thousand five hundred forty-three',
    '40000': 'forty thousand',
    '41567': 'forty-one thousand five hundred sixty-seven',
    '43000': 'forty-three thousand',
    '45678': 'forty-five thousand six hundred seventy-eight',
    '46789': 'forty-six thousand seven hundred eighty-nine',
    '48000': 'forty-eight thousand',
    '50005': 'fifty thousand five',
    '51234': 'fifty-one thousand two hundred thirty-four',
    '52345': 'fifty-two thousand three hundred forty-five',
    '53678': 'fifty-three thousand six hundred seventy-eight',
    '54890': 'fifty-four thousand eight hundred ninety',
    '56789': 'fifty-six thousand seven hundred eighty-nine',
    '58000': 'fifty-eight thousand',
    '60012': 'sixty thousand twelve',
    '61456': 'sixty-one thousand four hundred fifty-six',
    '62890': 'sixty-two thousand eight hundred ninety',
    '64321': 'sixty-four thousand three hundred twenty-one',
    '65432': 'sixty-five thousand four hundred thirty-two',
    '67890': 'sixty-seven thousand eight hundred ninety',
    '69000': 'sixty-nine thousand',
    '70015': 'seventy thousand fifteen',
    '71234': 'seventy-one thousand two hundred thirty-four',
    '72543': 'seventy-two thousand five hundred forty-three',
    '73678': 'seventy-three thousand six hundred seventy-eight',
    '74567': 'seventy-four thousand five hundred sixty-seven',
    '75900': 'seventy-five thousand nine hundred',
    '76890': 'seventy-six thousand eight hundred ninety',
    '78543': 'seventy-eight thousand five hundred forty-three',
    '80000': 'eighty thousand',
    '81234': 'eighty-one thousand two hundred thirty-four',
    '82567': 'eighty-two thousand five hundred sixty-seven',
    '83678': 'eighty-three thousand six hundred seventy-eight',
    '84900': 'eighty-four thousand nine hundred',
    '86789': 'eighty-six thousand seven hundred eighty-nine',
    '89000': 'eighty-nine thousand',
    '90012': 'ninety thousand twelve',
    '91234': 'ninety-one thousand two hundred thirty-four',
    '92890': 'ninety-two thousand eight hundred ninety',
    '94567': 'ninety-four thousand five hundred sixty-seven',
    '95678': 'ninety-five thousand six hundred seventy-eight',
    '96890': 'ninety-six thousand eight hundred ninety',
    '98000': 'ninety-eight thousand',
    '100001': 'one hundred thousand one',
    '101234': 'one hundred one thousand two hundred thirty-four',
    '102345': 'one hundred two thousand three hundred forty-five',
    '103567': 'one hundred three thousand five hundred sixty-seven',
    '104678': 'one hundred four thousand six hundred seventy-eight',
    '105890': 'one hundred five thousand eight hundred ninety',
    '106543': 'one hundred six thousand five hundred forty-three',
    '108900': 'one hundred eight thousand nine hundred',
    '110000': 'one hundred ten thousand',
    '112345': 'one hundred twelve thousand three hundred forty-five',
    '114567': 'one hundred fourteen thousand five hundred sixty-seven',
    '116789': 'one hundred sixteen thousand seven hundred eighty-nine',
    '119000': 'one hundred nineteen thousand',
    '121234': 'one hundred twenty-one thousand two hundred thirty-four',
    '123456': 'one hundred twenty-three thousand four hundred fifty-six',
    '125789': 'one hundred twenty-five thousand seven hundred eighty-nine',
    '129000': 'one hundred twenty-nine thousand',
    '130000': 'one hundred thirty thousand'
}