diccionario = {
    'my favorite language __ English': 'is',
    'there __ two dogs in the park': 'are',
    'the book __ on the table': 'is',
    'the flowers __ in the vase': 'are',
    'this __ my best friend': 'is',
    'the chairs __ in the living room': 'are',
    'my phone __ on the desk': 'is',
    'the children __ playing outside': 'are',
    'this __ a beautiful painting': 'is',
    'the stars __ shining brightly': 'are',
    'the cat __ under the bed': 'is',
    'the keys __ on the kitchen counter': 'are',
    'the answer __ correct': 'is',
    'the apples __ fresh': 'are',
    'my favorite food __ pizza': 'is',
    'the students __ in the classroom': 'are',
    'the coffee __ hot': 'is',
    'the houses __ on the hill': 'are',
    'this __ my favorite song': 'is',
    'the mountains __ covered in snow': 'are',
    'the laptop __ on the chair': 'is',
    'the windows __ open': 'are',
    'this __ a sunny day': 'is',
    'the birds __ singing in the trees': 'are',
    'the movie __ interesting': 'is',
    'the pictures __ on the wall': 'are',
    'the pen __ on the floor': 'is',
    'the clouds __ gray': 'are',
    'the ice cream __ delicious': 'is',
    'the books __ heavy': 'are',
    'my favorite color __ blue': 'is',
    'the cars __ parked outside': 'are',
    'the soup __ hot': 'is',
    'the phones __ charging': 'are',
    'this __ my backpack': 'is',
    'the shoes __ clean': 'are',
    'the cake __ ready': 'is',
    'the gifts __ on the table': 'are',
    'my favorite season __ summer': 'is',
    'the lights __ off': 'are',
    'the bottle __ empty': 'is',
    'the animals __ in the zoo': 'are',
    'this __ an easy task': 'is',
    'the toys __ scattered everywhere': 'are',
    'the tea __ warm': 'is',
    'the people __ waiting in line': 'are',
    'the box __ full of chocolates': 'is',
    'the students __ hardworking': 'are',
    'the weather __ perfect today': 'is',
    'the fruits __ ripe': 'are',
    'this __ my first time here': 'is',
    'the lamps __ beautiful': 'are',
    'the dog __ friendly': 'is',
    'the kittens __ playful': 'are',
    'my house __ near the beach': 'is',
    'the gardens __ well maintained': 'are',
    'this __ a comfortable chair': 'is',
    'the shelves __ dusty': 'are',
    'the music __ too loud': 'is',
    'the paintings __ colorful': 'are',
    'this __ a new project': 'is',
    'the machines __ running smoothly': 'are',
    'the bus __ late': 'is',
    'the drivers __ waiting for passengers': 'are',
    'this __ an old photo': 'is',
    'the necklaces __ expensive': 'are',
    'the train __ on time': 'is',
    'the tracks __ clear': 'are',
    'the pizza __ in the oven': 'is',
    'the chairs __ neatly arranged': 'are',
    'my favorite drink __ coffee': 'is',
    'the flowers __ blooming': 'are',
    'this __ a quiet neighborhood': 'is',
    'the streets __ empty': 'are',
    'the soup __ tasty': 'is',
    'the children __ excited': 'are',
    'my goal __ to learn English': 'is',
    'the bags __ heavy': 'are',
    'this __ an amazing story': 'is',
    'the fans __ cheering loudly': 'are',
    'the water __ cold': 'is',
    'the players __ ready for the game': 'are',
    'this __ the best restaurant in town': 'is',
    'the cookies __ delicious': 'are',
    'the milk __ in the fridge': 'is',
    'the shirts __ on the rack': 'are',
    'my favorite place __ the library': 'is',
    'the papers __ on the desk': 'are',
    'the weather __ unpredictable': 'is',
    'the boxes __ labeled correctly': 'are',
    'the school __ nearby': 'is',
    'the buildings __ tall': 'are',
    'this __ the last question': 'is',
    'the answers __ on the board': 'are',
    'the game __ fun': 'is',
    'the puzzles __ challenging': 'are',
    'my hobby __ reading': 'is',
    'the exercises __ helpful': 'are',
    'the coffee __ on the table': 'is',
    'the books __ borrowed from the library': 'are',
    'this __ a small town': 'is',
    'the roads __ busy': 'are',
    'the meeting __ tomorrow': 'is',
    'the presentations __ ready': 'are',
    'this __ my dream job': 'is',
    'the coworkers __ friendly': 'are',
    'the homework __ easy': 'is',
    'the questions __ difficult': 'are',
    'this __ the right answer': 'is',
    'the mistakes __ minor': 'are',
    'the result __ impressive': 'is',
    'the opportunities __ endless': 'are',
    'this __ my favorite memory': 'is',
    'the decorations __ beautiful': 'are',
    'the car __ brand new': 'is',
    'the keys __ missing': 'are',
    'my favorite fruit __ mango': 'is',
    'the oranges __ sweet': 'are',
    'the office __ closed today': 'is',
    'the lights __ dimmed': 'are',
    'this __ a challenging task': 'is',
    'the teammates __ supportive': 'are',
    'the box __ too heavy to lift': 'is',
    'the labels __ in order': 'are',
    'this __ a delicious dish': 'is',
    'the spices __ fragrant': 'are',
    'my project __ almost finished': 'is',
    'the documents __ filed properly': 'are',
    'this __ an unexpected result': 'is',
    'the factors __ significant': 'are'
}
