diccionario = {
    'there __ a sofa': 'is', 'there __ two chairs': 'are', 'there __ a table': 'is',
    'there __ five books on the shelf': 'are', 'there __ a picture on the wall': 'is',
    'there __ six apples in the basket': 'are', 'there __ a dog in the garden': 'is',
    'there __ three cars in the parking lot': 'are', 'there __ a lamp on the desk': 'is',
    'there __ four windows in the room': 'are', 'there __ a computer on the table': 'is',
    'there __ ten students in the class': 'are', 'there __ a pen on the floor': 'is',
    'there __ two bottles of water on the counter': 'are', 'there __ a clock on the wall': 'is',
    'there __ several trees in the park': 'are', 'there __ a cake in the fridge': 'is',
    'there __ three birds on the tree': 'are', 'there __ a toy under the bed': 'is',
    'there __ seven days in a week': 'are', 'there __ a notebook in my bag': 'is',
    'there __ many stars in the sky': 'are', 'there __ a bus at the station': 'is',
    'there __ four cups on the shelf': 'are', 'there __ a hat on the chair': 'is',
    'there __ two keys on the table': 'are', 'there __ a spider in the corner': 'is',
    'there __ eight people in the meeting': 'are', 'there __ a pizza in the oven': 'is',
    'there __ a flower in the vase': 'is', 'there __ three pillows on the bed': 'are',
    'there __ a sandwich on the plate': 'is', 'there __ several letters in the mailbox': 'are',
    'there __ a rabbit in the cage': 'is', 'there __ five pens in the pencil case': 'are',
    'there __ a painting above the fireplace': 'is', 'there __ some milk in the fridge': 'is',
    'there __ two umbrellas by the door': 'are', 'there __ a candle on the table': 'is',
    'there __ ten desks in the classroom': 'are', 'there __ a cat in the basket': 'is',
    'there __ three toys on the floor': 'are', 'there __ a mirror in the bathroom': 'is',
    'there __ many books on the shelf': 'are', 'there __ a phone on the counter': 'is',
    'there __ a piano in the living room': 'is', 'there __ several plates in the sink': 'are',
    'there __ a coffee mug on the desk': 'is', 'there __ four children in the yard': 'are',
    'there __ a notebook on the chair': 'is', 'there __ six students in the library': 'are',
    'there __ a remote control on the sofa': 'is', 'there __ two jackets on the rack': 'are',
    'there __ a glass of water on the table': 'is', 'there __ many pictures on the wall': 'are',
    'there __ a mouse in the kitchen': 'is', 'there __ three pens on the desk': 'are',
    'there __ a clock in the hallway': 'is', 'there __ a globe on the shelf': 'is',
    'there __ eight chairs around the table': 'are', 'there __ a ticket on the counter': 'is',
    'there __ five lamps in the room': 'are', 'there __ a plant in the corner': 'is',
    'there __ a TV in the living room': 'is', 'there __ several towels in the closet': 'are',
    'there __ a notebook on the floor': 'is', 'there __ three oranges in the bowl': 'are',
    'there __ a newspaper on the bench': 'is', 'there __ two socks under the bed': 'are',
    'there __ a jacket on the chair': 'is', 'there __ a gift on the table': 'is',
    'there __ four suitcases in the car': 'are', 'there __ a backpack on the couch': 'is',
    'there __ a bottle of juice in the fridge': 'is', 'there __ many people at the bus stop': 'are',
    'there __ a book on the windowsill': 'is', 'there __ two cushions on the sofa': 'are',
    'there __ a wallet on the table': 'is', 'there __ five cups of coffee on the counter': 'are',
    'there __ a plant on the balcony': 'is', 'there __ many cars on the street': 'are',
    'there __ a clock on the mantelpiece': 'is', 'there __ several hats on the rack': 'are',
    'there __ a strawberry on the cake': 'is', 'there __ two pencils on the notebook': 'are',
    'there __ a magazine on the armchair': 'is', 'there __ three donuts in the box': 'are',
    'there __ a painting on the wall': 'is', 'there __ several bottles on the shelf': 'are',
    'there __ a phone on the bed': 'is', 'there __ a basket of fruit on the counter': 'is',
    'there __ four cats in the yard': 'are', 'there __ a remote on the coffee table': 'is',
    'there __ many chairs in the auditorium': 'are', 'there __ a towel on the chair': 'is',
    'there __ a basketball on the court': 'is', 'there __ a bird in the cage': 'is',
    'there __ several paintings on the gallery walls': 'are', 'there __ two dogs in the yard': 'are',
    'there __ a pair of glasses on the desk': 'is', 'there __ a notebook beside the computer': 'is',
    'there __ a lamp by the bedside': 'is', 'there __ many clouds in the sky': 'are',
    'there __ a pillow on the couch': 'is', 'there __ seven bottles in the crate': 'are',
    'there __ a picture frame on the shelf': 'is', 'there __ a vase of flowers on the counter': 'is',
    'there __ three boxes in the storage room': 'are', 'there __ a coat on the hook': 'is',
    'there __ a soccer ball in the bag': 'is', 'there __ several toys in the playroom': 'are',
    'there __ a pair of shoes under the chair': 'is', 'there __ a pen and a pencil on the notebook': 'are',
    'there __ two glasses on the table': 'are', 'there __ a chair in the corner': 'is',
    'there __ five birds in the sky': 'are', 'there __ a painting above the bed': 'is',
    'there __ many lights in the stadium': 'are', 'there __ a snack on the counter': 'is',
    'there __ a pair of headphones on the chair': 'is', 'there __ a calendar on the wall': 'is',
    'there __ two newspapers on the table': 'are', 'there __ a teddy bear on the bed': 'is',
    'there __ a mirror on the dresser': 'is', 'there __ six towels in the basket': 'are',
    'there __ a laptop on the table': 'is', 'there __ three pairs of shoes on the floor': 'are'
}
